import {
    AccountTask,
    CreateAccountMutation,
    CreateAccountMutationVariables,
    CreateTaskMutation,
    CreateTaskMutationVariables,
    DeleteTaskMutation,
    DeleteTaskMutationVariables,
    ListAccountsQuery,
    ListAccountsQueryVariables,
    ListTasksQuery,
    ListTasksQueryVariables,
    UpdateAccountMutation,
    UpdateAccountMutationVariables,
} from "../API";
import { createAccount, createTask, deleteTask, updateAccount } from "../graphql/mutations";
import { listAccounts, listTasks } from "../graphql/queries";

export type UpdateAccountOptions =
    | {
          is_admin?: 0 | 1;
          taskIdsToRemove?: AccountTask["task_id"][];
          tasksToAdd?: AccountTask[];
      }
    | { tasks: AccountTask[]; is_admin?: 0 | 1 };


export type GraphQLMutations = {
    [createAccount]: {
        response: CreateAccountMutation;
        variables: CreateAccountMutationVariables;
    };
    [createTask]: {
        // NB: According to autogenerated stubs/types should have __typename, but actually doesn't
        response: CreateTaskMutation & {createTask: Omit<CreateTaskMutation["createTask"], "__typename">};
        variables: CreateTaskMutationVariables;
    };
    [deleteTask]: {
        response: DeleteTaskMutation,
        variables: DeleteTaskMutationVariables
    }
    [updateAccount]: {
        response: UpdateAccountMutation;
        variables: UpdateAccountMutationVariables;
    };
};

export type GraphQLQueries = {
    [listAccounts]: {
        response: ListAccountsQuery;
        variables: ListAccountsQueryVariables;
    };
    [listTasks]: {
        response: ListTasksQuery;
        variables: ListTasksQueryVariables;
    };
};

export type GraphQLOperations = GraphQLQueries & GraphQLMutations;
